services:
  micro:
    image: sylver/micro:main
    restart: unless-stopped
    volumes:
      - ./micro.yaml:/usr/src/micro/micro.yaml
      - ./data:/data

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=youshallnotpass # change this!
      - POSTGRES_USER=micro
      - POSTGRES_DB=micro
    volumes:
      - ./.pg-data:/var/lib/postgresql/data
      
  tunnel:
    container_name: tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run micro
    volumes:
      - ./.cloudflared:/etc/cloudflared
      - ./tunnel.yaml:/etc/cloudflared/config.yml