# THIS FILE IS FOR DEVELOPMENT ONLY.
# If you want complete examples on how to host micro, see the /examples directory.
# Persistence is not setup for this postgres instance.
version: "3"
services:
  postgres:
    image: postgres:12-alpine
    container_name: micro_postgres
    restart: unless-stopped
    ports:
      - 127.0.0.1:5433:5432
    environment:
      - POSTGRES_USER=micro
      - POSTGRES_PASSWORD=youshallnotpass
      - POSTGRES_DB=micro
